import React from "react"
import Button from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/FNVYXYuplFl2mNZi9YzuQ9/Components?node-id=1%3A12",
  {
    props: {
      label: figma.string("label"),
      variant: figma.enum("variant", {
        primary: "primary",
        secondary: "secondary",
      }),
      isPill: figma.boolean("isPill"),
    },
    example: (props) => <Button label={props.label} isPill={props.isPill} />,
  },
)
